### ISSUE TITLE
`unidentified alias "production"...` if production is not defined first in file

### ISSUE THREAD

**Issue by jamesmartinduffy** [vngrs/konfig#10]
First of all, great extension. This does exactly what I was looking for.

If I copy/paste the example YAML config from the docs, I get the following:

```coffee
coffee> config = require("konfig")()
JS-YAML: unidentified alias "production" at line 13, column 20:
        <<: *production
                       ^
```

If I move `production` config above `staging`, it works fine. Is it possible to define an alias after referencing it? If not, the docs should be updated to reflect that. Cheers!

**Comment by alidavut** [comment]
I updated the doc. Thanks.
