### ISSUE TITLE
Bump coffee-script dependency to use generators

### ISSUE THREAD

**Issue by brenwell** [vngrs/konfig#11]
Hey there, thanks for the lib.

I am using this for my simple koa app. And I found that the coffeescript version was pre-generators and was causing me some headaches. I believe 1.9 was the version that included them. I swapped out the coffeescript in the lib for the newest one and its solved all my problems. If you get time and interest maybe you wanna bump the dependency?

Thanks

**Comment by alidavut** [comment]
I think cson library caused this problem. I updated the dependencies and published new version. I'm closing this issue, if you encounter this again we can reopen the subject.

**Comment by brenwell** [comment]
Yes I think thats correct actually cson was too blame,  hopefully they have bumped dependencies. Thanks  alot.

**Comment by brenwell** [comment]
Yep looks like they have. https://github.com/bevry/cson/blob/master/package.json.
